### PR TITLE
Add team biographies

### PR DESCRIPTION
**Pull request by TheHiddenLayer**
# Add Team Biographies

### Change log
- Everyone added their personal bios
- I went in and made the links to personal websites embedded within the markdown (looks a lil more professional like that)
- Added emojis here and there to add some visual color cuz markdown is so bland

### P.R. Acceptance Criteria
- No typos or obvious visual errors.
- Contains all content that the Canvas assignment asks for.

### CODE REVIEW

**Comment by TheHiddenLayer** [comment]
## Example Comment
@TheHiddenLayer ☜ I can tag people! 😱

It's good to review each other's code by commenting on each other's Pull Requests (just like I'm commenting on my own, we can have full-on discussions in comment threads). 

BTW, this is all markdown.

### Future Plans
> Might look into setting up a continuous integration pipeline as the project evolves just to get a robot to check over the basics of our work before asking the rest of our team members to. Check [this link](https://circleci.com/docs/2.0/build-processing/#what-are-pipelines) out!

**Comment by TheHiddenLayer** [comment]
Has my approval. Looks good everyone!

**Review by TheHiddenLayer — COMMENTED** [review]
Has my approval. Looks good everyone! @thedestroyer4312 let me know when you've given it a look over -- it might be a good idea for you and me to co-approve the larger PR's from now on. Let's remember to practice that good habit of *`squashing`* and merging so master doesn't get flooded with minor/insignificant commits 👍

**Comment by thedestroyer4312** [comment]
Pull request looks good to me. I'm going to approve it now.

**Pull request merged**
